services:
  - type: web
    name: jahani-frontend
    runtime: static
    region: singapore
    buildCommand: npm install && npm run build
    staticPublishDirectory: dist
    envVars:
      - key: VITE_API_URL
        value: "https://jahani-mart-backend.onrender.com/api"
