services:
  - type: web
    name: jahani-frontend
    runtime: static
    region: singapore
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishDirectory: dist
    routes:
      - type: rewrite
        source: /sitemap.xml
        destination: /sitemap.xml
      - type: rewrite
        source: /robots.txt
        destination: /robots.txt
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: "https://jahani-mart-backend.onrender.com/api"
